#spring.application.name=Journal App
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.uri=mongodb+srv://alirizwan05681_db_user:u34dQPkbPn4AOqMyl@cluster0.68aofs7.mongodb.net/journaldb?retryWrites=true&w=majority

#spring.data.mongodb.database=journaldb
#spring.data.mongodb.auto-index-creation=true

spring:
  data:
    mongodb:
      uri: mongodb+srv://alirizwan05681_db_user:u34dQPkbPn4AOqMyl@cluster0.68aofs7.mongodb.net/journaldb?retryWrites=true&w=majority
      database: journaldb
      auto-index-creation: true


server:
  port: 8081
  servlet:
    context-path: /journal